version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8201:8201"
    volumes:
      - ./config:/vault/config
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201/'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
